### ISSUE TITLE
Change project name to "cpumap-pping"

### ISSUE THREAD

**Issue by rchac** [thebracket/cpumap-pping-hackjob#1]
I currently have cpumap-pping working with LibreQoS v1.3 on my local system.
![image](https://user-images.githubusercontent.com/22501920/197296289-a3cfeeae-4fde-4932-b0a3-736b43805e17.png)

Eager to bring in those changes to v1.3-alpha, but before I do, I was hoping to see if you can change the name to "cpumap-pping" when you have time so I can hardcore the paths correctly. =)

**Comment by thebracket** [comment]
That looks great! I've renamed the project, so I'll close the issue. Thanks!
