### ISSUE TITLE
Tag Nag

### ISSUE THREAD

**Issue by dtaht** [thebracket/cpumap-pping-hackjob#3]
can you tag and release 1.0.0 please?

There a way to do CI and build this for more than one arch?

**Comment by thebracket** [comment]
I'll move to 1.0 after resolving #4 - which was discovered last night under heavy load by a user.

**Comment by thebracket** [comment]
I knew it was too good to be true that I'd make it from RC1 to 1.0 without an issue being reported. I've got the blocking issue's fix past local-VM testing, next step is to test with some live data here.

**Comment by thebracket** [comment]
The patch worked wonderfully, so I've tagged the 1.0 release.
