### ISSUE TITLE
xdp_pping userspace command spins at 100% under heavy load

### ISSUE THREAD

**Issue by thebracket** [thebracket/cpumap-pping-hackjob#4]
Blocks #3 - delaying the 1.0 release to fix this.

Under 5gbit/s load, 17 CPUs passing traffic - the userspace reporting program correctly issues RTT reports - and then appears to hang at 100% CPU usage. It's actually spinning trying to remove all of the reported data - and eventually clears up - but lock contention during the cleanup is terrible.

**Comment by thebracket** [comment]
The latest commit:

```
Note that you have to reboot to use this patch, it
modifies the structure of pinned kernel maps.

1) rtt_tracker is now a BPF_MAP_TYPE_LRU_HASH, meaning that
   old entries are automatically removed. This provides
   two performance advantages:

   a) The tracker cannot run out of space. Old entries
      are automatically deleted in kernel-space.

   b) The tracker is pre-allocated when the BPF program
      starts - leading to more stable performance, no
      reallocs or kernel-side memory allocation.

2) rtt_tracker now contains a "recycle_time" field.
   When created, recycle_time is NOW() + 30 seconds.

3) When an rtt_tracker has a complete set of samples,
   and will no longer accept new samples:
   the current time is checked against recycle_time.
   If 30 seconds have elapsed, the rtt_tracker entry
   has its RTT results zeroed, and next_entry set back
   to 0 - it's ready for new data. recycle_time is
   once again updated to NOW + 30 seconds.

4) xdp_pping (userspace) no longer does ANY deletion,
   making it impossible for it to be caught in a spin
   cycle (it would eventually terminate, but can take
   a REALLY long time). Instead, it just dumps the current
   sample data and terminates.

5) rtt_tracker has gained a "fresh_data" field. This is
   zero on entry creation or entry recycle. When data is
   written to the tracker entry, fresh_data is set to 1.

6) xdp_pping only prints data with a non-zero fresh_data
   flag. This prevents old entries that created some data,
   never spoke again and weren't LRU recycled because of
   lack of insert-pressure from polluting results with
   repeated data.

Test status: local VM testing only.
```

In other words, the part of the program that appeared to lock up no longer exists at all, and is replaced by in-kernel data recycling. Performance is a little more stable in my small VM testing.

**Comment by thebracket** [comment]
Next steps are to merge this with the slightly modified version I have in production (it reports the local IP address of each flow), and test it there under load. I should be able to do this today.

**Comment by dtaht** [comment]
Are you pushing 17Gbit in production? :awe:

Edit: 5Gbit. Precoffee... Still, quite a lot.

**Comment by thebracket** [comment]
I'm not (I get to push a humble 2gbit/s, over 10 CPUs in a ProxMox VM), but the customer (trying to avoid naming names in a public ticket or posting any of the data they sent) ran into it. They pushed 1.3 early, and ran into the issue at 5.1 gbit/s of live data (they peak at 11).

**Comment by dtaht** [comment]
My dumb question is, on what core is all the cleanup happening? Can it take place over multiple cores?

**Comment by thebracket** [comment]
That's actually part of the problem; userspace calls into BPF are synced, but aren't synced *between* calls - and there's not a graceful way to say "kill everything in the map" safely (that I can find, at least). So I side-stepped the entire issue and have each CPU clean up the map as it goes, which *is* synchronized/safe due to BPF not being interruptible.

**Comment by thebracket** [comment]
It just passed local test 1 (edit: didn't mean to tag issue 1), which is 5 VMs pounding data as fast as possible (both directions) across a virtual 3 CPUs (limited to try and encourage issues). I'll be trying it on some live data at lunch (we have a reliable sag in throughput at noon CST, so we'll test then)

**Comment by dtaht** [comment]
https://www.youtube.com/watch?v=KOO5S4vxi0o

**Comment by thebracket** [comment]
I have the code in production. At this time of day, we're only pulling around 1gbit/s, but it's very spry.
![image](https://user-images.githubusercontent.com/14896751/201721199-daf52d2a-40bb-4de7-b35e-7c2f7477f262.png)

And from a coffee shop on our network (small link, shared with lots of students frantically "getting their homework done"):
![image](https://user-images.githubusercontent.com/14896751/201721254-baac9d96-cd68-499f-a493-02c14c460f01.png)

**Comment by dtaht** [comment]
Really pretty. Do the fat bars have any meaning? This is medians?

**Comment by dtaht** [comment]
Sol love to hear you test from coffee shops... I have so many stories from those days 1999-2006... when we finally broke free from the data center and got table service.... and met girls...

**Comment by thebracket** [comment]
It's medians, and the fat bars are "Herbert can't figure out how to get
this styling engine to stop making bars pretty". The y axis is "number of
flows within this RTT band".

The coffee-shop is a long-term client, and serves the best Turkish-style
coffee in town. I fix their stuff often enough that they hand me free
coffee when I walk through the door. :-)

**Comment by dtaht** [comment]
That's how it worked in the ole days. We traded out free wifi in exchange for free coffee in 120union and jahva house in santa cruz.
So glad the tradition continues.

**Comment by thebracket** [comment]
The latest patch is looking great in production.
